Support gathering a version from go.mod (#4)
Add support for the `tools.go` pattern for managing "go install"-able
binaries by reading the versions from go.mod.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -130,10 +130,53 @@ jobs:
           fi
 
           if [ "${VERSION}" != "v0.7.0" ]; then
-            echo "version != 'v0.7.0'"
+            echo "::error version != 'v0.7.0'"
             exit 1
           fi
         env:
           CACHED: ${{ steps.install-version.outputs.cached }}
           NAME: ${{ steps.install-version.outputs.name }}
           VERSION: ${{ steps.install-version.outputs.version }}
+
+      - name: Install version-file
+        id: install-version-file
+        uses: ./
+        with:
+          package: github.com/daixiang0/gci
+          version-file: testdata/go.mod
+
+      - name: Check install version-file
+        run: |
+          echo cached=${CACHED}
+          echo name=${NAME}
+          echo version=${VERSION}
+
+          if [ "${NAME}" != "gci" ]; then
+            echo "::error name != 'gci'"
+            exit 1
+          fi
+
+          if [ "${VERSION}" != "v0.13.4" ]; then
+            echo "::error version != 'v0.13.4'"
+            exit 1
+          fi
+        env:
+          CACHED: ${{ steps.install-version-file.outputs.cached }}
+          NAME: ${{ steps.install-version-file.outputs.name }}
+          VERSION: ${{ steps.install-version-file.outputs.version }}
+
+      # NEGATIVE TEST CASES BELOW
+
+      # - name: Install version-file missing
+      #   id: install-version-file-missing
+      #   uses: ./
+      #   with:
+      #     package: mvdan.cc/gofumpt
+      #     version-file: testdata/go.mod
+
+      # - name: Install version-file invalid
+      #   id: install-version-file-invalid
+      #   uses: ./
+      #   with:
+      #     package: mvdan.cc/gofumpt
+      #     version-file: testdata/go.sum
